### ISSUE TITLE
server doesn't work

### ISSUE THREAD

**Issue by yozhic** [0i0/geektoolio#3]
Hello. I'm trying to run `node app.js` but I'm getting this error
```
events.js:167
      throw er; // Unhandled 'error' event
      ^
 
Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at Object.<anonymous> (/Users/s/Library/Application Support/geektoolio/app.js:102:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```
So, the geektoolio doesn't show anything. What can I do to fix this?
(I'm on the High Sierra)

**Comment by 0i0** [comment]
This Repo is Deprecated please see https://github.com/0i0/nonky
